2022-02-25 15:26:33,902 INFO    MainThread:55133 [wandb_setup.py:_flush():71] setting env: {}
2022-02-25 15:26:33,902 INFO    MainThread:55133 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-25 15:26:33,902 INFO    MainThread:55133 [wandb_init.py:_log_setup():371] Logging user logs to /Users/stefan/Documents/Studium/CogSci in Osnabrück/Mehr/HiWi-Tätigkeiten/NBP/Content/Head2EyeMovement/Head2Eye/wandb/run-20220225_152633-2ro74wxv/logs/debug.log
2022-02-25 15:26:33,903 INFO    MainThread:55133 [wandb_init.py:_log_setup():372] Logging internal logs to /Users/stefan/Documents/Studium/CogSci in Osnabrück/Mehr/HiWi-Tätigkeiten/NBP/Content/Head2EyeMovement/Head2Eye/wandb/run-20220225_152633-2ro74wxv/logs/debug-internal.log
2022-02-25 15:26:33,903 INFO    MainThread:55133 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fb6bde67c10>
2022-02-25 15:26:33,903 INFO    MainThread:55133 [wandb_init.py:init():404] calling init triggers
2022-02-25 15:26:33,903 INFO    MainThread:55133 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-02-25 15:26:33,903 INFO    MainThread:55133 [wandb_init.py:init():424] re-initializing run, found existing run on stack: 2wdyz22j
2022-02-25 15:26:33,905 INFO    MainThread:55133 [wandb_run.py:finish():1457] finishing run sballe/Head2Eye/2wdyz22j
2022-02-25 15:26:33,906 INFO    MainThread:55133 [jupyter.py:save_history():429] not saving jupyter history
2022-02-25 15:26:33,906 INFO    MainThread:55133 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-25 15:26:33,907 INFO    MainThread:55133 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2022-02-25 15:26:33,909 INFO    MainThread:55133 [wandb_init.py:init():460] starting backend
2022-02-25 15:26:33,909 INFO    MainThread:55133 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-02-25 15:26:33,913 INFO    MainThread:55133 [backend.py:ensure_launched():216] starting backend process...
2022-02-25 15:26:33,920 INFO    MainThread:55133 [backend.py:ensure_launched():221] started backend process with pid: 56712
2022-02-25 15:26:33,924 INFO    MainThread:55133 [wandb_init.py:init():469] backend started and connected
2022-02-25 15:26:33,979 INFO    MainThread:55133 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-02-25 15:26:34,003 INFO    MainThread:55133 [wandb_init.py:init():533] updated telemetry
2022-02-25 15:26:34,041 INFO    MainThread:55133 [wandb_init.py:init():563] communicating current version
2022-02-25 15:26:35,586 INFO    MainThread:55133 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-02-25 15:26:35,588 INFO    MainThread:55133 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-02-25 15:26:36,128 INFO    MainThread:55133 [wandb_init.py:init():606] starting run threads in backend
2022-02-25 15:26:41,135 INFO    MainThread:55133 [wandb_run.py:_console_start():1810] atexit reg
2022-02-25 15:26:41,136 INFO    MainThread:55133 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-02-25 15:26:41,136 INFO    MainThread:55133 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-02-25 15:26:41,138 INFO    MainThread:55133 [wandb_run.py:_redirect():1745] Redirects installed.
2022-02-25 15:26:41,138 INFO    MainThread:55133 [wandb_init.py:init():633] run started, returning control to user process
2022-03-01 14:36:54,231 INFO    MainThread:55133 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-03-01 14:36:54,361 INFO    MainThread:55133 [wandb_run.py:_restore():1752] restore
2022-03-01 14:36:54,836 INFO    MainThread:55133 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 883
  total_bytes: 883
}

2022-03-01 14:36:55,188 INFO    MainThread:55133 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 883
  total_bytes: 883
}

2022-03-01 14:36:56,228 INFO    MainThread:55133 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 883
  total_bytes: 126214
}

2022-03-01 14:36:56,335 INFO    MainThread:55133 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 883
  total_bytes: 129920
}

